const {test,mock}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
process.env.DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'bot-http-'));
process.env.AUTH_DIR=path.join(process.env.DATA_DIR,'auth');
process.env.PORT='0';process.env.CHAVE_API='teste-local';delete process.env.LIMPAR_AUTH;
mock.timers.enable({apis:['Date'],now:new Date('2026-09-17T20:00:00Z')});
const jid='5593999001111@s.whatsapp.net';
fs.writeFileSync(path.join(process.env.DATA_DIR,'historicos.json'),JSON.stringify({[jid]:[{role:'atendente',text:'Mensagem da equipe',origem:'humano'}]}));
const bot=require('../index');
test('painel → API → cadastro → leitura e pausa global, sem WhatsApp real',async()=>{
  const servidor=bot.iniciarServidorHTTP(()=>null);
  await new Promise(resolve=>servidor.listening?resolve():servidor.once('listening',resolve));
  const url='http://127.0.0.1:'+servidor.address().port;
  const post=(rota,dados)=>fetch(url+rota,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chave:'teste-local',...dados})});
  const agenda={nome:'Maria da Silva',telefone:'5593999001111',horario:'Sábado 19 de setembro em Bela Vista do Caracol-PA às 11:30'};
  try {
    assert.equal((await fetch(url+'/api/dados')).status,401);
    assert.equal((await post('/api/agendamento-manual',{...agenda,nome:{invalido:true}})).status,400);
    assert.equal((await post('/api/agendamento-manual',{...agenda,horario:'Terça-feira 99 de setembro em Cidade Inventada-PA às 10:00'})).status,400);
    assert.equal((await post('/api/agendamento-manual',{...agenda,telefone:''})).status,400);
    assert.equal((await post('/api/agendamento-manual',agenda)).status,200);
    assert.equal((await post('/api/agendamento-manual',agenda)).status,200);
    const dados=await(await fetch(url+'/api/dados?chave=teste-local')).json();
    assert.equal(dados.agendamentos.length,1);assert.equal(dados.agendamentos[0].horario,agenda.horario);
    const conversa=await(await fetch(url+'/api/conversa?chave=teste-local&jid=5593999001111')).json();
    assert.equal(conversa.mensagens[0].text,'Mensagem da equipe');
    assert.equal((await post('/api/pausar-todos',{})).status,200);
    assert.equal(bot.iaPausada('5593999009999@s.whatsapp.net'),true);
    assert.equal(JSON.parse(fs.readFileSync(path.join(process.env.DATA_DIR,'controle-ia.json'))).pausada,true);
    assert.equal((await post('/api/retomar',{telefone:'5593999009999'})).status,409);
    assert.equal((await post('/api/retomar-todos',{})).status,200);
    assert.equal(bot.iaPausada('5593999009999@s.whatsapp.net'),false);
    assert.equal((await post('/api/enviar',{jid:'5593999001111',texto:'Teste'})).status,503);
    const arquivoEspera=path.join(process.env.DATA_DIR,'lista-espera-novo-progresso.json');
    const arquivoRetorno=path.join(process.env.DATA_DIR,'lista-espera-retornos.json');
    const paciente={nome:'Maria da Silva',telefone:'5593999001111',criadoEm:'2026-09-21T12:00:00Z',status:'aguardando_data'};
    fs.writeFileSync(arquivoEspera,JSON.stringify([paciente,{...paciente,nome:'João da Silva'}]));
    fs.writeFileSync(arquivoRetorno,JSON.stringify([{...paciente,cidade:'Xapuri-AC',status:'aguardando_retorno'}]));
    const espera=await(await fetch(url+'/api/dados?chave=teste-local')).json();
    const item=espera.listaEsperaNovoProgresso[0];
    assert.equal((await post('/api/espera-verificada',{chave:'errada',idEspera:item.idEspera,origemLista:item.origemLista,verificado:true})).status,401);
    assert.equal((await post('/api/espera-verificada',{idEspera:item.idEspera,origemLista:item.origemLista,verificado:'true'})).status,400);
    assert.equal((await post('/api/espera-verificada',{idEspera:item.idEspera,origemLista:item.origemLista,verificado:true})).status,200);
    const salva=JSON.parse(fs.readFileSync(arquivoEspera));
    assert.equal(salva[0].verificado,true);assert.equal(salva[1].verificado,undefined);
    assert.equal(salva[0].status,'aguardando_data');assert.equal(JSON.parse(fs.readFileSync(arquivoRetorno))[0].verificado,undefined);
    const atual=await(await fetch(url+'/api/dados?chave=teste-local')).json();
    assert.equal(atual.listaEsperaNovoProgresso[0].verificado,true);
    assert.equal(atual.listaEsperaNovoProgresso[0].idEspera,item.idEspera);
    assert.equal((await post('/api/espera-verificada',{idEspera:item.idEspera,origemLista:item.origemLista,verificado:false})).status,200);
    assert.equal(JSON.parse(fs.readFileSync(arquivoEspera))[0].verificado,false);
    const retorno=atual.listaEsperaRetornos[0];
    assert.equal((await post('/api/espera-verificada',{idEspera:retorno.idEspera,origemLista:retorno.origemLista,verificado:true})).status,200);
    assert.equal(JSON.parse(fs.readFileSync(arquivoRetorno))[0].verificado,true);
  }finally{await new Promise(resolve=>servidor.close(resolve));}
});
test('contexto mantém mais de 80 falas recentes sem confundir mensagens da equipe',()=>{
  const mensagens=Array.from({length:100},(_,i)=>({role:i%2?'atendente':'cliente',text:'Mensagem '+i,criadoEm:'2026-09-15T12:00:00Z'}));
  const contexto=bot.contextoParaIA(mensagens);
  assert.equal(contexto.length,100);assert.equal(contexto[0].text,'Mensagem 0');
});
