const {test,mock}=require('node:test');const assert=require('node:assert/strict');const fs=require('fs'),os=require('os'),path=require('path');
process.env.DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'bot-propostas-'));process.env.AUTH_DIR=path.join(process.env.DATA_DIR,'auth');delete process.env.LIMPAR_AUTH;
mock.timers.enable({apis:['Date'],now:new Date('2026-09-17T20:00:00Z')});
const jid=n=>`55939999777${n}@s.whatsapp.net`;const hist={};for(let n=1;n<=6;n++)hist[jid(n)]=[{role:'cliente',text:'Laura Campos Siqueira'},{role:'cliente',text:'Caracol'}];hist[jid(2)].push({role:'cliente',text:'Sim eu consigo ir na sexta-feira na escola Bela Vista do Caracol'});hist[jid(5)].push({role:'cliente',text:'Tem para sexta feira'});
fs.writeFileSync(path.join(process.env.DATA_DIR,'historicos.json'),JSON.stringify(hist));
const bot=require('../index');const dia19='Sábado 19 de setembro em Bela Vista do Caracol-PA';const dia18='Sexta-feira 18 de setembro em Bela Vista do Caracol-PA';const arq=path.join(process.env.DATA_DIR,'agendamentos.json');const ler=()=>fs.existsSync(arq)?JSON.parse(fs.readFileSync(arq)):[];const reset=()=>fs.writeFileSync(arq,'[]');
const marca=h=>'###AGENDAR###'+JSON.stringify({nome:'Laura Campos Siqueira',horario:h});const propor=(n,h)=>bot.processarResposta(marca(h),jid(n),{exigirAceite:true});
test('nome e Caracol geram proposta objetiva sem gravar nem pedir deslocamento',()=>{reset();const texto=propor(1,`${dia19} às 08:00`);assert.match(texto,/posso agendar/);assert.match(texto,/19 de setembro, às 08:00/);assert.doesNotMatch(texto,/consegue se deslocar|confirmado/);assert.equal(ler().length,0)});
test('sim salva exatamente o horário proposto mesmo após outra pessoa ocupar a cota',()=>{fs.writeFileSync(arq,JSON.stringify(Array.from({length:10},(_,n)=>({nome:'Outro Teste '+n,telefone:'55939911111'+n,horario:`${dia19} às 08:00`}))));const texto=bot.responderAceiteProposta(jid(1),'Sim');assert.match(texto,/Agendamento confirmado/);assert.equal(ler().at(-1).horario,`${dia19} às 08:00`);assert.equal(bot.carregarPropostas()[jid(1)],undefined)});
test('escolha explícita de sexta corrige até uma proposta errada de sábado',()=>{reset();const texto=propor(2,`${dia19} às 08:00`);assert.match(texto,/18 de setembro/);assert.equal(ler().length,0);bot.responderAceiteProposta(jid(2),'Sim');assert.equal(ler()[0].horario,`${dia18} às 08:00`)});
test('recusa não grava e permite outro horário no mesmo dia',()=>{reset();propor(3,`${dia19} às 08:00`);bot.responderAceiteProposta(jid(3),'Não, prefiro às 15:00');assert.equal(ler().length,0);assert.equal(bot.carregarPropostas()[jid(3)].recusada,true);propor(3,`${dia19} às 15:00`);bot.responderAceiteProposta(jid(3),'Pode ser');assert.equal(ler()[0].horario,`${dia19} às 15:00`)});
test('sim com ressalva ou pergunta não confirma',()=>{reset();propor(4,`${dia19} às 08:00`);bot.responderAceiteProposta(jid(4),'Sim, mas só de tarde');assert.equal(ler().length,0);bot.responderAceiteProposta(jid(4),'Sim?');assert.equal(ler().length,0)});
test('pedido de mudança mantém reserva antiga até aceitar sexta-feira',()=>{reset();fs.writeFileSync(arq,JSON.stringify([{nome:'Laura Campos Siqueira',telefone:jid(5).split('@')[0],horario:`${dia19} às 08:00`}])) ;const texto=bot.processarResposta('###REAGENDAR###'+JSON.stringify({nome:'Laura Campos Siqueira',horarioAntigo:`${dia19} às 08:00`,horarioNovo:`${dia18} às 09:00`}),jid(5),{exigirAceite:true});assert.match(texto,/posso agendar/);assert.equal(ler()[0].horario,`${dia19} às 08:00`);bot.responderAceiteProposta(jid(5),'Sim');assert.equal(ler().length,1);assert.equal(ler()[0].horario,`${dia18} às 09:00`)});
test('sim não confirma proposta que expirou',()=>{reset();propor(6,`${dia19} às 08:00`);mock.timers.setTime(Date.parse('2026-09-19T13:00:00Z'));const texto=bot.responderAceiteProposta(jid(6),'Sim');assert.match(texto,/anterior não está mais disponível/);assert.equal(ler().length,0);assert.equal(bot.carregarPropostas()[jid(6)].horario,`${dia19} às 14:00`)});
test('endereço de Caracol contendo Trairão não invalida o sim',()=>{assert.equal(bot.historicoConfirmaDeslocamento([{role:'atendente',text:'Nosso atendimento em Bela Vista do Caracol será no dia 19, na EMEIF Bela Vista de Caracol, Zona Rural, Trairão-PA. Você consegue se deslocar e comparecer nesse local?'},{role:'cliente',text:'Sim'}],'Bela Vista do Caracol-PA'),true)});

test('alternativa preserva o nome completo já coletado mesmo se IA abreviar',()=>{mock.timers.setTime(Date.parse('2026-09-17T20:00:00Z'));reset();propor(4,`${dia19} às 08:00`);bot.responderAceiteProposta(jid(4),'Não, outro horário');const texto=bot.processarResposta('###AGENDAR###'+JSON.stringify({nome:'Laura',horario:`${dia19} às 15:00`}),jid(4),{exigirAceite:true});assert.match(texto,/Laura Campos Siqueira/);assert.match(texto,/15:00/);bot.responderAceiteProposta(jid(4),'Sim, pode agendar');assert.equal(ler()[0].nome,'Laura Campos Siqueira')});

test('conversa com saída estruturada cria proposta e o aceite grava sem nova pergunta à IA',async()=>{
 mock.timers.setTime(Date.parse('2026-09-17T20:00:00Z'));reset();fs.writeFileSync(path.join(process.env.DATA_DIR,'propostas-agendamento.json'),'{}');
 const original=global.fetch;let chamadas=0;const respostas=[];global.fetch=async(_url,opt)=>{chamadas++;const body=JSON.parse(opt.body);assert.equal(body.generationConfig.responseMimeType,'application/json');return{ok:true,json:async()=>({candidates:[{content:{parts:[{text:JSON.stringify({acao:'propor',nomes:['Laura Campos Siqueira'],horario:`${dia19} às 08:00`,horarioAntigo:'',resposta:''})}]}}]})}};
 const sock={sendPresenceUpdate:async()=>{},sendMessage:async(_jid,m)=>{respostas.push(m.text);return{key:{id:'teste-local'}}}};
 try{await bot.responder(sock,jid(1),'Caracol');assert.match(respostas.at(-1),/posso agendar/);assert.equal(ler().length,0);await bot.responder(sock,jid(1),'Sim eu consigo');assert.equal(chamadas,1);assert.equal(ler().length,1);assert.match(respostas.at(-1),/Agendamento confirmado/)}finally{global.fetch=original}
});
