module.exports = {
  NOME_EMPRESA: "Visão Cidadão",
  NOME_ATENDENTE: "Gessica",
  ENDERECO: "O ponto de atendimento exato é confirmado pela equipe conforme a cidade do dia escolhido",
  ENDERECOS_POR_CIDADE: {
    "Sena Madureira-AC": "Comunidade Batista Vida — Rua Padre Egídio, 856, Centro",
    "Xapuri-AC": "Igreja AD Brás Madureira — Rua Cel. Brandão, 1805, Bairro Cerâmica",
    "Boca do Acre-AM": "Clínica Spaço Profissional, no Piquiá",
    "Acrelândia-AC": "Igreja AD Brás Madureira — Rua Minas Gerais",
    "Guajará-Mirim-RO": "SINTERO — Avenida 15 de Novembro (de frente ao Hotel Quinzão)",
    "Distrito de Extrema-RO": "Igreja Missionária IMUB — Rua Boa Esperança, Bairro Planalto",
    "Moraes de Almeida-PA": "Escola César Almeida — Distrito de Moraes Almeida, s/n, Rodovia BR-163, km 1.185, Itaituba-PA",
  },
  CIDADE: "Acre, Amazonas, Rondônia e Pará (mutirão itinerante — uma cidade por dia)",
  HORARIOS: [
    "Quinta-feira 13 de agosto em Sena Madureira-AC às 08:00",
    "Quinta-feira 13 de agosto em Sena Madureira-AC às 09:00",
    "Quinta-feira 13 de agosto em Sena Madureira-AC às 10:00",
    "Quinta-feira 13 de agosto em Sena Madureira-AC às 14:00",
    "Quinta-feira 13 de agosto em Sena Madureira-AC às 15:00",
    "Quinta-feira 13 de agosto em Sena Madureira-AC às 16:00",
    "Sexta-feira 14 de agosto em Sena Madureira-AC às 08:00",
    "Sexta-feira 14 de agosto em Sena Madureira-AC às 09:00",
    "Sexta-feira 14 de agosto em Sena Madureira-AC às 10:00",
    "Sexta-feira 14 de agosto em Sena Madureira-AC às 14:00",
    "Sexta-feira 14 de agosto em Sena Madureira-AC às 15:00",
    "Sexta-feira 14 de agosto em Sena Madureira-AC às 16:00",
    "Sábado 15 de agosto em Xapuri-AC às 08:00",
    "Sábado 15 de agosto em Xapuri-AC às 09:00",
    "Sábado 15 de agosto em Xapuri-AC às 10:00",
    "Sábado 15 de agosto em Xapuri-AC às 14:00",
    "Sábado 15 de agosto em Xapuri-AC às 15:00",
    "Sábado 15 de agosto em Xapuri-AC às 16:00",
    "Domingo 16 de agosto em Boca do Acre-AM às 08:00",
    "Domingo 16 de agosto em Boca do Acre-AM às 09:00",
    "Domingo 16 de agosto em Boca do Acre-AM às 10:00",
    "Domingo 16 de agosto em Boca do Acre-AM às 14:00",
    "Domingo 16 de agosto em Boca do Acre-AM às 15:00",
    "Domingo 16 de agosto em Boca do Acre-AM às 16:00",
    "Segunda-feira 17 de agosto em Boca do Acre-AM às 08:00",
    "Segunda-feira 17 de agosto em Boca do Acre-AM às 09:00",
    "Segunda-feira 17 de agosto em Boca do Acre-AM às 10:00",
    "Segunda-feira 17 de agosto em Boca do Acre-AM às 14:00",
    "Segunda-feira 17 de agosto em Boca do Acre-AM às 15:00",
    "Segunda-feira 17 de agosto em Boca do Acre-AM às 16:00",
    "Terça-feira 18 de agosto em Acrelândia-AC às 08:00",
    "Terça-feira 18 de agosto em Acrelândia-AC às 09:00",
    "Terça-feira 18 de agosto em Acrelândia-AC às 10:00",
    "Terça-feira 18 de agosto em Acrelândia-AC às 14:00",
    "Terça-feira 18 de agosto em Acrelândia-AC às 15:00",
    "Terça-feira 18 de agosto em Acrelândia-AC às 16:00",
    "Quinta-feira 20 de agosto no Distrito de Extrema-RO às 08:00",
    "Quinta-feira 20 de agosto no Distrito de Extrema-RO às 09:00",
    "Quinta-feira 20 de agosto no Distrito de Extrema-RO às 10:00",
    "Quinta-feira 20 de agosto no Distrito de Extrema-RO às 14:00",
    "Quinta-feira 20 de agosto no Distrito de Extrema-RO às 15:00",
    "Quinta-feira 20 de agosto no Distrito de Extrema-RO às 16:00",
    "Sexta-feira 21 de agosto em Guajará-Mirim-RO às 08:00",
    "Sexta-feira 21 de agosto em Guajará-Mirim-RO às 09:00",
    "Sexta-feira 21 de agosto em Guajará-Mirim-RO às 10:00",
    "Sexta-feira 21 de agosto em Guajará-Mirim-RO às 14:00",
    "Sexta-feira 21 de agosto em Guajará-Mirim-RO às 15:00",
    "Sexta-feira 21 de agosto em Guajará-Mirim-RO às 16:00",
    "Sábado 22 de agosto em Guajará-Mirim-RO às 08:00",
    "Sábado 22 de agosto em Guajará-Mirim-RO às 09:00",
    "Sábado 22 de agosto em Guajará-Mirim-RO às 10:00",
    "Sábado 22 de agosto em Guajará-Mirim-RO às 14:00",
    "Sábado 22 de agosto em Guajará-Mirim-RO às 15:00",
    "Sábado 22 de agosto em Guajará-Mirim-RO às 16:00",
    "Segunda-feira 14 de setembro em Moraes de Almeida-PA às 08:00",
    "Segunda-feira 14 de setembro em Moraes de Almeida-PA às 09:00",
    "Segunda-feira 14 de setembro em Moraes de Almeida-PA às 10:00",
    "Segunda-feira 14 de setembro em Moraes de Almeida-PA às 14:00",
    "Segunda-feira 14 de setembro em Moraes de Almeida-PA às 15:00",
    "Segunda-feira 14 de setembro em Moraes de Almeida-PA às 16:00",
    "Terça-feira 15 de setembro em Moraes de Almeida-PA às 08:00",
    "Terça-feira 15 de setembro em Moraes de Almeida-PA às 09:00",
    "Terça-feira 15 de setembro em Moraes de Almeida-PA às 10:00",
    "Terça-feira 15 de setembro em Moraes de Almeida-PA às 14:00",
    "Terça-feira 15 de setembro em Moraes de Almeida-PA às 15:00",
    "Terça-feira 15 de setembro em Moraes de Almeida-PA às 16:00",
    "Quarta-feira 16 de setembro em Moraes de Almeida-PA às 08:00",
    "Quarta-feira 16 de setembro em Moraes de Almeida-PA às 09:00",
    "Quarta-feira 16 de setembro em Moraes de Almeida-PA às 10:00",
    "Quarta-feira 16 de setembro em Moraes de Almeida-PA às 14:00",
    "Quarta-feira 16 de setembro em Moraes de Almeida-PA às 15:00",
    "Quarta-feira 16 de setembro em Moraes de Almeida-PA às 16:00",
    "Quinta-feira 17 de setembro em Moraes de Almeida-PA às 08:00",
    "Quinta-feira 17 de setembro em Moraes de Almeida-PA às 09:00",
    "Quinta-feira 17 de setembro em Moraes de Almeida-PA às 10:00",
    "Quinta-feira 17 de setembro em Moraes de Almeida-PA às 14:00",
    "Quinta-feira 17 de setembro em Moraes de Almeida-PA às 15:00",
    "Quinta-feira 17 de setembro em Moraes de Almeida-PA às 16:00",
  ],
  INFORMACOES: `
- O exame de vista é 100% GRATUITO. Não vendemos nada, não tem custo nenhum em momento algum.
- A pessoa precisa levar um documento de identificação com foto (CPF ou RG) no dia do atendimento.
- Atendemos qualquer idade.
- É um mutirão itinerante: passamos por uma cidade diferente do Acre, Amazonas e Rondônia a cada dia, conforme a agenda.
- A pessoa deve escolher a data e a cidade da lista de horários disponíveis mais perto dela.
- Não há limite de vagas por horário: todos os horários da lista estão sempre disponíveis, mesmo que outras pessoas já tenham marcado o mesmo horário.
- Depois do exame, o médico passa um atestado de horas pra pessoa levar no trabalho, na escola ou onde precisar, comprovando a ausência.
- Exames e avaliações que fazemos: retinografia, biomicroscopia, tonometria, refração computadorizada, avaliação cirúrgica, encaminhamentos e laudos cirúrgicos.
`,
  GEMINI_API_KEY: process.env.GEMINI_API_KEY || "COLE-SUA-CHAVE-AQUI",
  NUMERO_BOT: process.env.NUMERO_BOT || "5500000000000",
  PORTA_HTTP: process.env.PORT || process.env.PORTA_HTTP || 3000,
  CHAVE_API: process.env.CHAVE_API || "troque-esta-chave-123",
  FB_ACCESS_TOKEN: process.env.FB_ACCESS_TOKEN || "",
  FB_AD_ACCOUNT_ID: process.env.FB_AD_ACCOUNT_ID || "",
  FB_API_VERSION: process.env.FB_API_VERSION || "v21.0",
};
